### ISSUE TITLE
How can I change from SQLite back to my original database?

### ISSUE THREAD

**Issue by CMYang95** [WordPress/sqlite-database-integration#128]
"I installed the SQLite Database Integration plugin on WordPress. When I activated it, my website redirected to the WordPress installation page. If I try to install it again, the following error occurs:

Error occurred while creating tables or indexes...
Query was: 'CREATE TABLE iQg_users ( ID bigint(20) unsigned NOT NULL auto_increment, user_login varchar(60) NOT NULL default \'\', user_pass varchar(255) NOT NULL default \'\', user_nicename varchar(50) NOT NULL default \'\', user_email varchar(100) NOT NULL default \'\', user_url varchar(100) NOT NULL default \'\', user_registered datetime NOT NULL default \'0000-00-00 00:00:00\', user_activation_key varchar(255) NOT NULL default \'\', user_status int(11) NOT NULL default \'0\', display_name varchar(250) NOT NULL default \'\', PRIMARY KEY (ID), KEY user_login_key (user_login), KEY user_nicename (user_nicename), KEY user_email (user_email) ) DEFAULT CHARACTER SET utf8mb4'
Error message is:

Now I want to switch my website back to my original database. How should I proceed with this?"

**Comment by aristath** [comment]
You can simply delete the `wp-content/db.php` file 👍
