### ISSUE TITLE
information_schema and other metadata queries aren't correct

### ISSUE THREAD

**Issue by OllieJones** [WordPress/sqlite-database-integration#20]
The information_schema and metadata queries need work.  Many! plugins use them,  https://wpdirectory.net/search/01GTQD2377VCEWY8WHAMK8PC0K

Testing criteria: at least the top 20 plugins using the information_schema work properly.  (Excluding site-clone, backup, caching, etc).

**Comment by OllieJones** [comment]
@aristath I hope you don't mind me working on this kind of compatibility-layer code. If so, just tell me and I'll step back,

Is this the right repo to contain this work? I'm not sure what your plan for the monorepo is.

It seems wise to think through what this rewriter will look like when it has 20 or more query-editing rules. For the ecosystem  (plugin and template authors) it will be really helpful to have a filter-oriented framework they can field-extend if they need to.

Some of the necessary rewrites are doable with your lex / parse scheme. Others (information_schema) are going to require parsing the query and figuring out how to get the required data another way. Finally, there are queries that depend on dialect-specific features, like the query used to delete expired transients.

**Comment by aristath** [comment]
> @aristath I hope you don't mind me working on this kind of compatibility-layer code. If so, just tell me and I'll step back,

Of course I don't mind... The more the married, and I value your input tremendously! 👍 

> Is this the right repo to contain this work? I'm not sure what your plan for the monorepo is.

For the time being, this is the right repo, yes.
The plan is to move this back to the monorepo (see https://github.com/WordPress/performance/issues/661), but that will take a few weeks, as we first need to complete all the infrastructure necessary to deploy plugins etc from there.
Until that happens, we can use this repo for all development, and then we'll be porting the code in the PL monorepo when the time comes

**Comment by OllieJones** [comment]
Advanced Database Cleaner doesn't yet clean expired transients.
