### ISSUE TITLE
Ensure the plugin works smoothly when activating it on a site with Performance Lab SQLite module

### ISSUE THREAD

**Issue by felixarntz** [WordPress/sqlite-database-integration#33]
We need to test that the plugin works in combination with the Performance Lab plugin's SQLite module. Specifically, if a site already has the Performance Lab SQLite module active, we need to ensure that activating the standalone plugin at that point works correctly.

For example:
* It should not throw a fatal error due to e.g. duplicate functions.
* It should continue to operate smoothly even if the Performance Lab's SQLite module `db.php` drop-in is currently placed.

The work here potentially involves making changes to both the PL module and the standalone plugin. Since the standalone plugin is going to be the source of truth going forward (see https://github.com/WordPress/performance/issues/661#issuecomment-1522047097), we should try to limit the changes needed in the PL module though.

**Comment by felixarntz** [comment]
cc @aristath @joemcgill

**Comment by felixarntz** [comment]
Thanks @aristath for the update!

I made one comment https://github.com/WordPress/sqlite-database-integration/commit/6e5b9e87588aa42e55282118d393cfedab734ead#r112417524 on the commit for something that would be good to fix, but other than that it looks great to me.

When are you planning to release the plugin version that includes this logic?

> What changes would we like to make to the PL plugin? Should we remove the SQLite implementation from there, and instead add an admin notice prompting users to install the standalone plugin?

Yes, but we also need to consider a smooth migration path. For example, I think we need to first launch a version with the admin notice, and only then launch a version where the module is actually removed, just to give people a chance to update before we would potentially break their site by removing the module.

**Comment by aristath** [comment]
> When are you planning to release the plugin version that includes this logic?

Already done 🎉
