### ISSUE TITLE
Error en modo depuración

### ISSUE THREAD

**Issue by ximosa** [WordPress/sqlite-database-integration#54]
EN MODO DEPURACION TENGO ESTE ERROR

Deprecated: strtoupper(): Passing null to parameter  # 1 ($string) of type string is deprecated in /bitnami/wordpress/wp-content/plugins/sqlite-database-integration/wp-includes/sqlite/class-wp-sqlite-token.php on line 222

Algún experto me dice porque?

Saludos

**Comment by bradstimpson** [comment]
+1

**Comment by aristath** [comment]
PR in https://github.com/WordPress/sqlite-database-integration/pull/132 👍
