### ISSUE TITLE
Make the plugin a must-use

### ISSUE THREAD

**Issue by nestarz** [WordPress/sqlite-database-integration#55]
Hi,

How can I make this plugin a must use in a mu-plugins folder ?

It leads to a critical error when I move the folder in this one.

Best

**Comment by predaytor** [comment]
Change `plugins` to `mu-plugins` in db.php file.
![Screenshot_16](https://github.com/WordPress/sqlite-database-integration/assets/32335730/36166b33-5124-4ad0-9159-528117918485)
