### ISSUE TITLE
Site Health: utf8mb4 requires a MySQL update

### ISSUE THREAD

**Issue by javiercasares** [WordPress/sqlite-database-integration#6]
When the plugin is active, a "Performance" improvement alert appears in Site Health:

```
UTF8MB4 is the character set WordPress prefers for database storage because it safely supports the widest set of characters and encodings, including Emoji, enabling better support for non-English languages.

WordPress’ utf8mb4 support requires MySQL version 5.5.3 or greater. Please contact your server administrator.
```

Maybe, the plugin should disable this message, and get another saying that SQLite is being used.

**Comment by aristath** [comment]
Thank you for checking the plugin @javiercasares!
Fixed the issue and I'll release an update later today 👍
