### ISSUE TITLE
Add PHP Compatibility checking

### ISSUE THREAD

**Issue by schlessera** [WordPress/sqlite-database-integration#63]
To avoid issues like https://github.com/WordPress/sqlite-database-integration/pull/62 in the future, it would be great to include the `phpcompatibility/php-compatibility` package and set it to check and enforce compatibility with PHP 5.6+.

**Comment by aristath** [comment]
I raised the minimum required version of the plugin to PHP7 last week, and just now I raised the versions of some packages and fixed a few issues that were reported :+1:
