### ISSUE TITLE
Undefined constant "DB_NAME"

### ISSUE THREAD

**Issue by gospodinbodurov** [WordPress/sqlite-database-integration#84]
PHP 8.3.4
Wordpress 6.4.3

2024/03/29 21:47:21 [error] 5784#5784: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "DB_NAME" in /var/www/html/wp-admin/includes/class-wp-site-health.php:3581
Stack trace:
#0 /var/www/html/wp-admin/includes/class-wp-site-health.php(2648): WP_Site_Health->should_suggest_persistent_object_cache()
#1 /var/www/html/wp-admin/includes/class-wp-site-health.php(194): WP_Site_Health->get_test_persistent_object_cache()
#2 /var/www/html/wp-admin/includes/class-wp-site-health.php(139): WP_Site_Health->perform_test()
#3 /var/www/html/wp-includes/class-wp-hook.php(324): WP_Site_Health->enqueue_scripts()
#4 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /var/www/html/wp-admin/admin-header.php(118): do_action()
#7 /var/www/html/wp-admin/site-health.php(96): require_once('...')
#8 {main}
  thrown in /var/www/html/wp-admin/includes/class-wp-site-health.php on line 3581" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /wp-admin/site-health.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/www.sock:", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/wp-admin/plugins.php?plugin_status=all&paged=1&s"

**Comment by aristath** [comment]
Thank you for reporting this!
It _should_ be fixed now (though I could not replicate the issue).
The fix will be included in the next release 👍
